krishnaacharyaa/wanderlust

frontend/src/pages/add-blog.tsx

Adding Responsive Layout to add-blog page
add-blog page is not responsive. Now, adding responsiveness to add-blog page according to Laptop, Tablet, Mobile.
Mobile:
Tablet:
Laptop:
- Closed #15  

fix: Make the add page responsive

---

package.json

This PR introduces color enhancements to the script, enhancing readability and aesthetics. 
In this PR, I have made the following changes to the `package.json` file to enhance the developer experience:
- Modified the concurrently command to include backend and frontend names.
- Implemented different colors for frontend and backend console output.
**Before**
**After**
**Closes #32**

fix: Improved concurrently command for better readability of logs/errors

---

frontend/src/pages/home-page.tsx

Changed the jpeg bg image to webp file eliminating 5-6 seconds and crucial resources that was being taken to load a bg image.
Hosted the converted jpeg to webp file on imgbb to save on the overall build site keeping in mind that we will never the change the bg image, the home page now loads much faster and looks better.
[OLD AND NEW GIFS](https://drive.google.com/drive/folders/1p8ZtBz0ykdiUA2-KEQi7BMzymZgbyjZi?usp=drive_link)
**Closes #28**

fix: Fix the homepage bg image long load time

---

.github/ISSUE_TEMPLATE/config.yml

Add configuration file
Helps in choosing the issue template
NA
NA

chore: Created config.yml

---

frontend/src/components/modal.tsx
frontend/src/constants/images.ts
frontend/src/pages/add-blog.tsx

Updated image modal to allow users to select any of the 7 images from the webp format instead of randomizing.
In this pull request, I've modified the image modal functionality to enhance user experience. Now, users can specifically choose from any of the 7 available images in the webp format instead of the previous randomization. This change was implemented to give users more control over the visuals they want to interact with. I have also fixed the code according to the feedback received in the previous PR.
https://drive.google.com/drive/folders/14JFGZFLu-vtUvZdi7CmX4zrihCY0Lv21
Please find the new video in the drive (Updated from the last PR)
Closes #49

enhance: #49 Add button inside image url input to generate random images 

---

.gitignore
backend/.babelrc
backend/.eslintrc.json
backend/controllers/posts-controller.js
backend/package-lock.json
backend/package.json
backend/routes/posts.js
backend/tests/unit/controllers/posts-controller.test.js
backend/utils/constants.js

This PR is a continuation of PR #48 
In this PR,
1. Improved project structure by moving controllers from the ` routes ` folder to a dedicated ` controllers ` folder. The existing controller functions have been moved from the routes folder to this new location. 
2. Created setup for tests adding unit using jest and setup for babel, prettier
3. Added unit tests for various backend controller functions (as discussed in PR #48)
4. Improved code by adding validations in the required controllers (as discussed in PR #48)
- validation for "All fields are required"
- validation for "image url extensions"
- validation for "select categories not more that 3"
- while search by category - ensure category is valid
6. Improved controllers to pass all required testcases
Closes #5

test-#5: Improved code for api handlers and added unit tests for backend controllers using jest

---

.gitignore
frontend/src/App.tsx
frontend/src/components/featured-post-card.tsx
frontend/src/components/latest-post-card.tsx
frontend/src/components/post-card.tsx
frontend/src/pages/add-blog.tsx
frontend/src/pages/details-page.tsx
frontend/src/utils/slug-generator.ts

**Introduced Slug Integration to Enhance URL Shari*ng.**
User not able to see post using shared URLs.
In details-page
const {state} = useLoaction();
This line of code uses destructuring to extract the state property from the object returned by the useLocation hook. The state property contains any state data that was passed along with the navigation.
The state passed via location.state in React Router is specific to the current session and is not maintained in the URL itself. When you navigate directly to a URL that includes a state from an external source (like a shared link), React Router won't have that state information available, and location.state will be undefined.
###Approach
We've updated our URLs to follow the format details-page/:title/:postId. This change enables us to extract …

feat-#55: Introduced Slug Integration to Enhance URL Sharing

---

frontend/src/components/post-card.tsx
frontend/src/components/skeletons/post-card-skeleton.tsx
frontend/src/pages/home-page.tsx

All posts alignment fixed
'All posts' title and the posts were not aligned properly, added CSS to fix the alignment according to figma design
_Enter the issue number of the bug(s) that this PR fixes_
Closes #81

css fixed for All posts

---

frontend/src/components/blog-feed.tsx
frontend/src/components/featured-post-card.tsx
frontend/src/components/latest-post-card.tsx
frontend/src/components/post-card.tsx
frontend/src/components/skeletons/featured-post-card-skeleton.tsx
frontend/src/components/skeletons/post-card-skeleton.tsx
frontend/src/pages/details-page.tsx
frontend/src/pages/home-page.tsx

Fixed Header Part for mobile screen and other CSS changes
CSS changes to fix Mobile and Tablet devices. Used Tailwind CSS to add mobile and tablet compatibility. Continued the changes for Issues #13 
Creating a issue for refactoring of all the md: to sm:
_Enter the issue number of the bug(s) that this PR fixes_
Closes #13

Fix - #13 Make the HomePage responsive for all the devices

---

frontend/src/pages/add-blog.tsx
frontend/src/pages/details-page.tsx

This PR fixes a bug where users have to scroll to find the footer.
This PR aims to enhance the user experience by removing the scroll on pages which has less content.
_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_
Closes #121

fix-#121: Fixed scroll to find footer bug

---

backend/controllers/auth-controller.js
backend/models/user.js
backend/package-lock.json
backend/package.json
backend/routes/auth.js
backend/server.js
backend/utils/constants.js
backend/utils/cookie_options.js

Implemented sign up , sign in and sign out controllers as well as route end points.
**You will need to configure .env of the backend before testing this. In the .env you need to add following variables**
```
JWT_SECRET = 
ACCESS_TOKEN_EXPIRES_IN = 
REFRESH_TOKEN_EXPIRES_IN = 
GAUTH_CLIENT_ID= Your Google oAuth 2.0 client id
GAUTH_CLIENT_SECRET= Your Google oAuth 2.0 client secret
GITHUB_CLIENT_ID = Your Github client id
GITHUB_CLIENT_SECRET = Your Github client secret
GAUTH_TOKEN_URL = "https://oauth2.googleapis.com/token"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
REDIRECTION_URL = This is the URL where user redirected with authorized code after Google / Github auth window
GAUTH_USER_URL = "https://www.googleapis.com/oauth2/v3/userinfo"
GITHUB_USER_URL = …
```

Feature-#128 implementing backend controllers and routes for authentication

---

frontend/src/components/blog-feed.tsx
frontend/src/components/featured-post-card.tsx
frontend/src/components/hero.tsx
frontend/src/components/latest-post-card.tsx
frontend/src/components/modal.tsx
frontend/src/components/post-card.tsx
frontend/src/index.css
frontend/src/layouts/header-layout.tsx
frontend/src/pages/add-blog.tsx
frontend/src/pages/home-page.tsx
frontend/src/utils/scaling-animation.ts

+ Added scale (zoom-in) animation to the blog card images on hover.
+ Implemented a smooth scale animation effect to enhance user experience when hovering over the blog card images.
+ This animation adds visual appeal and interactivity to the blog section, drawing attention to the content and encouraging user engagement.
+ Also, added onClick scale animation to the card.
https://github.com/krishnaacharyaa/wanderlust/assets/46074384/d5fae1bf-a2ce-41cf-87cb-2efd9b5254d2
+ Added subtle image animation on hover
+ Added cursor-text on headings and sub-headings

feat: image-and-card-animation

---

backend/server.js
frontend/src/components/featured-post-card.tsx
frontend/src/components/latest-post-card.tsx
frontend/src/components/modal.tsx
frontend/src/components/post-card.tsx
frontend/src/index.css
frontend/src/layouts/header-layout.tsx
frontend/src/pages/add-blog.tsx
frontend/src/pages/details-page.tsx

Fixed scaling animation which was only active on card hover instead of image hover.
+ Fixed scaling animation which was only active on card hover instead of image hover.
+ Optimized styles to utilize tailwind classes.
+ Added onClick scaling animation to go-back arrow for better interactivity

fix: scale animation active on card hover instead of image hover.

---

frontend/src/components/admin-container.tsx
frontend/src/components/admin-sidebar.tsx
frontend/src/components/blog-feed.tsx
frontend/src/components/hero.tsx
frontend/src/components/post-card.tsx
frontend/src/components/skeletons/post-card-skeleton.tsx
frontend/src/layouts/footer-layout.tsx
frontend/src/layouts/header-layout.tsx
frontend/src/pages/add-blog.tsx
frontend/src/pages/admin-blogs.tsx
frontend/src/pages/admin-users.tsx
frontend/src/pages/details-page.tsx
frontend/src/pages/home-page.tsx
frontend/src/pages/signin-page.tsx
frontend/src/pages/signup-page.tsx

This PR is for proper naming convention using sm: 
It was before at some places md: ,now by changing md: to sm:, we can clarify that these styles are targeted not just at medium-sized devices but also at smaller devices like tablets. This adjustment ensures that the styling is more accurately aligned with the intended range of devices.
Closes #102

enhancement-#102: Refactoring of all the md: to sm:

---

backend/controllers/auth-controller.js
backend/routes/auth.js

added isloggedin route for auth

add : added isloggedin for checking user

---

.husky/commit-msg
.husky/pre-commit
backend/api/index.js
backend/package.json
frontend/package.json
package.json

enhancement: #177 Added the husky of the project
I have created the .husky folder in the root inside the .husky folder i have defined two files one is for pre commit and another one is for commit-msg 
pre-commit: whenever the user trying to make the commit the pre commit will run first and format the staged file 
commit-msg: it is to check whether the given commit message is satisfy the contributor guideline i have written the code the checking whether is the commit is correct or not.
if these two files did not make any kind of error then commit successfully added in the local git repo otherwise not.
commit message is valid.
commit message is not valid.
- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING …

feat-#177: Added husky of the project

---

README.md

The fully new version of readme file
Changed readme.md according to requests
Closes #263

fix-#263: Update readme doc

---

frontend/src/layouts/header-layout.tsx

Add logo beside the title in navbar
Added the logo with title in navbar along with Link tag to redirect it to home page again.
Closes #387

fix-#387: added logo beside title in navbar

---

frontend/src/pages/signin-page.tsx

fixed view password alignment icon 
mobile view
Closes #397 
- [ yes] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

fix-#397: fixed view password button alignment

---

.github/CONTRIBUTING.md

chore: updated documentation
To make setting up of the project easier
Fixed the steps to setup the backend
Included the Redis setting up part and corrected the mongoDB setting up steps. 
Closes #141

chore-#141: Updated Documentation 

---

frontend/src/pages/signup-page.tsx

Since the signUp page lacked the show/hide password feature.
Made necessary changes in the signUp code to add the above mentioned feature.
none
Closes #427
- [yes] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

fix-#427: Login-Page
