krishnaacharyaa/wanderlust

frontend/src/pages/details-page.tsx

Adding Responsive Layout to details page
Adjusting Margin in detail-page. Now, adding responsiveness to details page according to Laptop, Tablet, Mobile.
Mobile:
Tablet:
Laptop:
- Closed #14 

fix: Make the Details Page responsive

---

backend/routes/posts.js
frontend/src/components/blog-feed.tsx

Rename a few API endpoint names to follow industry standards
There are some REST API naming conventions that the industry is used to and it's a good practice to follow best practices.
Check these out -
1. [REST API URI Naming Conventions and Best Practices](https://restfulapi.net/resource-naming/)
2. [Best practices for REST API design](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design)
3. [RESTful web API design](https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design)
In this change, I have -
1. Renamed `latestposts` and `featured-posts` sans `post` since we're already in the `/posts` resource category.
5. According to the conventions, use plural nouns unless it's a singleton resource. Here, for example, `categories/adventure` endpoint is …

refactor: Rename few API endpoints to follow industry standards

---

README.md

Change the styling of setup instructions for better readability
- Use block code for commands instead of inline code. It's easier to read, copy, and paste the commands. GitHub also has the copy button for block commands.
Copy button:
- Add instructions to import sample data from `sample_posts.json` file using `mongoimport` command.
- **Copy** (`cp .env.sample .env`) instead of **Rename** (`mv .env.sample .env`) because git will track it as a change and you will see .env.sample file as a deleted git object. On the other hand, since we have already ignored .env* files, git won't track it and we keep the sample file untouched.
No tracked changes here:

docs: Change the styling of setup instructions for better readability

---

frontend/src/components/blog-feed.tsx
frontend/src/components/featured-post-card.tsx
frontend/src/components/latest-post-card.tsx
frontend/src/components/post-card.tsx
frontend/src/components/ui/skeleton.tsx
frontend/src/index.css
frontend/src/pages/add-blog.tsx
frontend/src/pages/details-page.tsx
frontend/src/pages/home-page.tsx
frontend/tailwind.config.js

Adding Dark Theme feature in add blog, home page. 
In this project adding dark theme feature according to the browser theme.
Add blog page
Home page
Details page
- Closes #16

fix: Support Dark theme based on the web browser's theme

---

frontend/src/components/latest-post-card.tsx

Ui - button on the latest post card redirecting to a empty tab solved 
button on the latest post card redirecting to a empty tab solved . Removed the navigation functionality
Closes #80

fix-#80 ui button issue solved

---

frontend/src/components/theme-toggle-button.tsx

This PR is to fix the flickering issue of the theme toggle button
This issue has occured because the callback function inside the useEffect only runs after the dom mutations and browser paints the screen.So in order to fix that I used useLayoutEffect instead of useEffect as the provided callback inside the useLayoutEffect runs before the browser paints the screen.
https://github.com/krishnaacharyaa/wanderlust/assets/140341777/5384016a-f957-4e40-ad6f-6f01bccc58ae
Closes #98

Bugfix/98 In Theme-Toggle-Button #98

---

frontend/src/App.tsx
frontend/src/components/hero.tsx
frontend/src/components/skeletons/featured-post-card-skeleton.tsx
frontend/src/layouts/footer-layout.tsx
frontend/src/layouts/header-layout.tsx
frontend/src/pages/home-page.tsx
frontend/tailwind.config.js
frontend/vercel.json

This PR introduces modular approach by separating header-code in a new 'header-layout' file  rather than keeping into a single file (home-page).
This PR isolates the header-related code from the home-page file and moves it into a new header-layout file, along with all imported modules. It then integrates this header-layout as a component within the home-page file.
_Include any relevant images or diagrams that can help reviewers visualize the changes, if applicable_

refactor: Created a new header-layout file to segregate out header code.

---

frontend/src/components/blog-feed.tsx

BUGFIX#165 : The UI box on the tags in dark theme is removed and the UI now aligns well with the rest and there is no alignment change while changing from light to dark.
The issue was related to the UI miss alignment of the tags under category due to the addition of an box in the dark theme. The purpose of this pr is to remove the styling css of tags section in the dark theme to make it aligned with the light themed UI.
I first identified the location of the styling and then removed the dark theme clause from the inline style of tailwind css to remove the dark box in the UI
1) Earlier n left sidebar inside Categories Container there is a box showing, while change on Theme On Repetitive switch of Theme There can be seen under the "Categories Box", there is a box over "Tags" which was …

BUGFIX-#165: Categories Sidebar UI issue

---

frontend/src/components/skeletons/latest-post-card-skeleton.tsx

The latest postcard skeleton alignment bug was fixed.
The latest postcard skeleton now features a slightly wider Author and Date row, with the third row removed.
Closes [#110 ](https://github.com/krishnaacharyaa/wanderlust/issues/110)

fix-#110: Latest post card skeleton alignment bug fixed

---

backend/package-lock.json
frontend/package-lock.json
frontend/src/pages/add-blog.tsx

This PR allow authenticated users to create blog posts
This PR addresses an issue where authenticated users were unable to create blog posts despite having valid and unexpired tokens. The problem manifested as an error toast displaying "Something went wrong. Please try again later!" when authenticate users attempted to create a post.
Now authenticate users can create blog post until and unless tokens are valid and unexpired. And if tokens get expired or invalid, we simply display toastify "Your session has expired, please login again!" and redirects to homepage with conditional rendering.
Closes #249

fix-#249: Now authenticate users able to create blog post.

---

frontend/src/layouts/header-layout.tsx

This PR aims to display icons in mobile screen + resolves header alignment.
This PR is basically makes the buttons hidden in mobile screen so that icons can be visible. And gives some styling to make header aligned with overall application.
Current behavior as expected :-
closes #258

fix-#258: Now icons are visible in mobile screen instead of both button + icons ( login, logout and creat post) and aligned header too.

---

frontend/package.json
package.json

Summary
whenever we are clone the repo and make some commit the .husky(pre-commit) hook did not work.
Description
The reason is we need to download the husky dependency then only .husky folder get initialized but we did not mention the husky dependency neither frontend package.json nor backend package.json. the husky dependency only present in the the root package.json file. now i have written the prepare script in the frontend package.json file it will automatically install entire node module in the root folder.
Prerequisites
[ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

feat-#177: cleared the husky bug

---

frontend/src/components/featured-post-card.tsx

##Summary
Added background-color & border to the skeleton card of blog post.
##Description
In the dark mode there is different background color for the card that represents the blog post but for the light mode it blends with white background, so changed the background color to slate-50 with border to differentiate it from the white background.
**Before:**
**After:**
closes #270

fix-#270: Added the border and the background-color to differentiate white background of the blog post card.

---

frontend/src/App.tsx
frontend/src/components/theme-toggle-button.tsx
frontend/src/pages/not-found.tsx
frontend/src/utils/theme-changer.ts

Fixed the issue of the theme changing to light mode on page refresh in the add blogs page by adding the class "dark" to the document if the theme is set to "dark" in local storage.
The issue occurred because the class list did not include "dark" while in dark mode, so I added it when the theme is set to "dark" in local storage.
Closes #159

fix-#159 : Configured Theme changes to light mode on page refresh in add blogs page

---

frontend/src/components/category-pill.tsx
frontend/src/components/post-card.tsx

Fixed the different height issues of All post sections.
The cards had different heights, causing inconsistency in the design. So added a Text Truncation (...) property on overflow on the Category Pill and sliced the category array into just  first 3 pills, so that it will stay in one line and won't grow to the next line to increase the size of the card.
Closes #220

fix-#220: Fixed Heights of All Post Section's cards

---

frontend/eslint.config.js

i have updated the eslint.config.js file
to avoid the unnecessary error like jsx must be in the scope
- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

chore: update the eslint.config.js file

---

frontend/src/components/skeletons/post-card-skeleton.tsx

Inlining posts and making it responsive.
This PR is according to changes made in post-card-skeleton.tsx to make padding properly and making changes to handle properly in all the screens, added pr-2 for padding and added w-16 along with w-full for adding full-width on smaller screens too.
Closes #108

fix-#108: Fixed bug by adding responsiveness and inlining the skeleton.

---

backend/middlewares/error-middleware.js
frontend/src/__tests__/integration/home.test.tsx
frontend/src/pages/add-blog.tsx
frontend/src/pages/signin-page.tsx
frontend/src/pages/signup-page.tsx
frontend/tailwind.config.js

Summary
modify the dark theme in the add blog page. and cleared the eslint error in both frontend and backend code.  
Description
I have changed the dark theme in the add blog component at the same time i have changed the color of login and signup button to white and cleared the eslint error in both frontend and backend code.
signin page
signup page
add blog page
- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

chore: modify the darktheme in the add blog and fixed the eslint error

---

backend/controllers/posts-controller.js
backend/routes/posts.js
frontend/src/assets/svg/arrow-right-black.svg
frontend/src/assets/svg/arrow-right-white.svg
frontend/src/assets/svg/arrow-right.svg
frontend/src/components/PostMobileViewCardSkeleton.tsx
frontend/src/components/PostMobileViewComponent.tsx
frontend/src/components/skeletons/related-post-card-skeleton.tsx
frontend/src/pages/details-page.tsx

added  related blogs section in detailed blog page
whenever user visited individual blog page..they can see related posts based on the categories in the blog page
desktop view
mobile view
Closes #392 
- [ yes] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

fix-#392: added related blogs section in detailed blog page

---

frontend/package.json
frontend/src/lib/types.ts
frontend/src/pages/add-blog.tsx
frontend/tailwind.config.js

I have converted the react traditional form to the react hook form.
I have done the react hook form to reduce the lot of re-renders at the same time users can easily identify the error while they are trying to add the blog in the application and for the  form validation i have used zod library.
https://github.com/krishnaacharyaa/wanderlust/assets/105500361/16fc38ec-686c-40dd-8ed6-64ed2595ff5d
_Enter the issue number of the bug(s) that this PR fixes_
- Template should be strictly **Closes <#77>**
- Example: Closes #77 
- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

fix-#77: changed the traditional form to react hook form

---

backend/controllers/posts-controller.js
backend/controllers/user-controller.js
frontend/eslint.config.js
frontend/src/App.tsx
frontend/src/components/admin-sidebar.tsx
frontend/src/components/skeletons/post-card-skeleton.tsx
frontend/src/layouts/header-layout.tsx
frontend/src/pages/admin-blogs.tsx
frontend/src/pages/admin-users.tsx
frontend/tailwind.config.js
frontend/tsconfig.json

Added admin UI to frontend
This PR adds all the admin functionality and UI to the frontend.
Checkout by logging in as admin.
/admin/user and /admin/blog route is implemented correctly.
A button in the header layout is also added to navigate to the admin dash board.
https://github.com/krishnaacharyaa/wanderlust/assets/109821078/7c5542ff-5108-4c60-8647-8710dea4635e
Closes #178

feat-#178: added admin UI to frontend

---

backend/controllers/user-controller.js
backend/middlewares/auth-middleware.js
backend/models/user.js
backend/types/role-type.js
backend/types/role-type.tsx
frontend/src/App.tsx
frontend/src/layouts/header-layout.tsx
frontend/src/pages/admin-users.tsx
frontend/src/types/role-type.tsx

I have added the role type (as an enum) in both the backend and frontend and replaced the "USER" and "ADMIN" types with `Role.User` and `Role.Admin`
_Explain in detail what this PR is all about. This should include the problem you're solving, the approach taken, and any technical details that reviewers need to know._
None
Closes [Issue #418](https://github.com/krishnaacharyaa/wanderlust/issues/418)

refactor-#418: Added role type in frontend and backend

---

frontend/src/components/blog-feed.tsx
frontend/src/components/latest-post-card.tsx

This PR aims to correct the icon color in dark mode to ensure consistency with the theme.
The current implementation of the icon color in dark mode does not match the overall theme, resulting in a less cohesive user interface. This PR addresses this issue by inverting the icon color in dark mode to ensure it aligns with the theme's color scheme.
Closes #275 Correct the icon color in dark mode

fix-#275: Correct the icon color in dark mode
